/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package heg.backendspring.api;

import heg.backendspring.models.EvaluationDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-23T19:52:08.287321300+01:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "evaluation", description = "Gestion des évaluations (examens, contrôles continus)")
public interface EvaluationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /course/{courseId}/addCC : Création d’un contrôle continu.
     * Crée une évaluation de type contrôle continu pour un cours.
     *
     * @param courseId Identifiant du cours. (required)
     * @param evaluationDto Données du contrôle continu. (required)
     * @return Contrôle continu créé. (status code 201)
     *         or Cours introuvable. (status code 404)
     *         or Erreur interne. (status code 500)
     */
    @Operation(
        operationId = "addCC",
        summary = "Création d’un contrôle continu.",
        description = "Crée une évaluation de type contrôle continu pour un cours.",
        tags = { "evaluation" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Contrôle continu créé.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = heg.backendspring.models.EvaluationDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cours introuvable."),
            @ApiResponse(responseCode = "500", description = "Erreur interne.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/course/{courseId}/addCC",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<heg.backendspring.models.EvaluationDto> addCC(
        @Parameter(name = "courseId", description = "Identifiant du cours.", required = true, in = ParameterIn.PATH) @PathVariable("courseId") Long courseId,
        @Parameter(name = "EvaluationDto", description = "Données du contrôle continu.", required = true) @Valid @RequestBody EvaluationDto evaluationDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : 200, \"name\" : \"Examen final\", \"date\" : \"2025-01-15\", \"coefficient\" : 2, \"courseId\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /course/{courseId}/addExam : Création d’un examen.
     * Crée une évaluation de type examen pour un cours.
     *
     * @param courseId Identifiant du cours. (required)
     * @param evaluationDto Données de l’examen. (required)
     * @return Examen créé. (status code 201)
     *         or Cours introuvable. (status code 404)
     *         or Erreur interne. (status code 500)
     */
    @Operation(
        operationId = "addExam",
        summary = "Création d’un examen.",
        description = "Crée une évaluation de type examen pour un cours.",
        tags = { "evaluation" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Examen créé.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = heg.backendspring.models.EvaluationDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cours introuvable."),
            @ApiResponse(responseCode = "500", description = "Erreur interne.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/course/{courseId}/addExam",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<heg.backendspring.models.EvaluationDto> addExam(
        @Parameter(name = "courseId", description = "Identifiant du cours.", required = true, in = ParameterIn.PATH) @PathVariable("courseId") Long courseId,
        @Parameter(name = "EvaluationDto", description = "Données de l’examen.", required = true) @Valid @RequestBody EvaluationDto evaluationDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : 200, \"name\" : \"Examen final\", \"date\" : \"2025-01-15\", \"coefficient\" : 2, \"courseId\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /course/{courseId}/evaluations : Création d’une évaluation.
     * Crée une nouvelle évaluation pour un cours.
     *
     * @param courseId Identifiant du cours. (required)
     * @param evaluationDto Données de l’évaluation. (required)
     * @return Évaluation créée. (status code 201)
     *         or Cours introuvable. (status code 404)
     *         or Erreur interne. (status code 500)
     */
    @Operation(
        operationId = "createEvaluation",
        summary = "Création d’une évaluation.",
        description = "Crée une nouvelle évaluation pour un cours.",
        tags = { "evaluation" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Évaluation créée.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = heg.backendspring.models.EvaluationDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cours introuvable."),
            @ApiResponse(responseCode = "500", description = "Erreur interne.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/course/{courseId}/evaluations",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<heg.backendspring.models.EvaluationDto> createEvaluation(
        @Parameter(name = "courseId", description = "Identifiant du cours.", required = true, in = ParameterIn.PATH) @PathVariable("courseId") Long courseId,
        @Parameter(name = "EvaluationDto", description = "Données de l’évaluation.", required = true) @Valid @RequestBody EvaluationDto evaluationDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : 200, \"name\" : \"Examen final\", \"date\" : \"2025-01-15\", \"coefficient\" : 2, \"courseId\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /course/{courseId}/evaluations/{evalId} : Suppression d’une évaluation.
     * Supprime une évaluation existante d’un cours.
     *
     * @param courseId Identifiant du cours. (required)
     * @param evalId Identifiant de l’évaluation. (required)
     * @return Évaluation supprimée. (status code 204)
     *         or Cours ou évaluation introuvable. (status code 404)
     *         or Erreur interne. (status code 500)
     */
    @Operation(
        operationId = "deleteEvaluation",
        summary = "Suppression d’une évaluation.",
        description = "Supprime une évaluation existante d’un cours.",
        tags = { "evaluation" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Évaluation supprimée."),
            @ApiResponse(responseCode = "404", description = "Cours ou évaluation introuvable."),
            @ApiResponse(responseCode = "500", description = "Erreur interne.")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/course/{courseId}/evaluations/{evalId}"
    )
    
    default ResponseEntity<Void> deleteEvaluation(
        @Parameter(name = "courseId", description = "Identifiant du cours.", required = true, in = ParameterIn.PATH) @PathVariable("courseId") Long courseId,
        @Parameter(name = "evalId", description = "Identifiant de l’évaluation.", required = true, in = ParameterIn.PATH) @PathVariable("evalId") Long evalId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /course/{courseId}/evaluations : Liste des évaluations d’un cours.
     * Retourne les évaluations associées à un cours.
     *
     * @param courseId Identifiant du cours. (required)
     * @return Liste d’évaluations retournée. (status code 200)
     *         or Cours introuvable. (status code 404)
     *         or Erreur interne. (status code 500)
     */
    @Operation(
        operationId = "getEvaluationsByCourse",
        summary = "Liste des évaluations d’un cours.",
        description = "Retourne les évaluations associées à un cours.",
        tags = { "evaluation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Liste d’évaluations retournée.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = heg.backendspring.models.EvaluationDto.class)))
            }),
            @ApiResponse(responseCode = "404", description = "Cours introuvable."),
            @ApiResponse(responseCode = "500", description = "Erreur interne.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/course/{courseId}/evaluations",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<heg.backendspring.models.EvaluationDto>> getEvaluationsByCourse(
        @Parameter(name = "courseId", description = "Identifiant du cours.", required = true, in = ParameterIn.PATH) @PathVariable("courseId") Long courseId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : 200, \"name\" : \"Examen final\", \"date\" : \"2025-01-15\", \"coefficient\" : 2, \"courseId\" : 1 }, { \"id\" : 200, \"name\" : \"Examen final\", \"date\" : \"2025-01-15\", \"coefficient\" : 2, \"courseId\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /course/{courseId}/evaluations/{evalId} : Mise à jour d’une évaluation.
     * Met à jour une évaluation existante d’un cours.
     *
     * @param courseId Identifiant du cours. (required)
     * @param evalId Identifiant de l’évaluation. (required)
     * @param evaluationDto Données mises à jour de l’évaluation. (required)
     * @return Évaluation mise à jour. (status code 200)
     *         or Cours ou évaluation introuvable. (status code 404)
     *         or Erreur interne. (status code 500)
     */
    @Operation(
        operationId = "updateEvaluation",
        summary = "Mise à jour d’une évaluation.",
        description = "Met à jour une évaluation existante d’un cours.",
        tags = { "evaluation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Évaluation mise à jour.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = heg.backendspring.models.EvaluationDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cours ou évaluation introuvable."),
            @ApiResponse(responseCode = "500", description = "Erreur interne.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/course/{courseId}/evaluations/{evalId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<heg.backendspring.models.EvaluationDto> updateEvaluation(
        @Parameter(name = "courseId", description = "Identifiant du cours.", required = true, in = ParameterIn.PATH) @PathVariable("courseId") Long courseId,
        @Parameter(name = "evalId", description = "Identifiant de l’évaluation.", required = true, in = ParameterIn.PATH) @PathVariable("evalId") Long evalId,
        @Parameter(name = "EvaluationDto", description = "Données mises à jour de l’évaluation.", required = true) @Valid @RequestBody EvaluationDto evaluationDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : 200, \"name\" : \"Examen final\", \"date\" : \"2025-01-15\", \"coefficient\" : 2, \"courseId\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
