/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package heg.backendspring.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-05T19:38:54.120291500+01:00[Europe/Zurich]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "tp-status", description = "Gestion des statuts des étudiants pour un TP")
public interface TpStatusApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /TPStatus/{statusId} : Suppression d’un statut pour un TP.
     * Supprime un TPStatus spécifique.
     *
     * @param statusId Identifiant du statut (TPStatus). (required)
     * @return Statut supprimé. (status code 204)
     * or Statut introuvable. (status code 404)
     * or Erreur interne. (status code 500)
     */
    @Operation(
            operationId = "deleteTPStatus",
            summary = "Suppression d’un statut pour un TP.",
            description = "Supprime un TPStatus spécifique.",
            tags = {"tp-status"},
            responses = {
                    @ApiResponse(responseCode = "204", description = "Statut supprimé."),
                    @ApiResponse(responseCode = "404", description = "Statut introuvable."),
                    @ApiResponse(responseCode = "500", description = "Erreur interne.")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/TPStatus/{statusId}"
    )

    default ResponseEntity<Void> deleteTPStatus(
            @Parameter(name = "statusId", description = "Identifiant du statut (TPStatus).", required = true, in = ParameterIn.PATH) @PathVariable("statusId") Long statusId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /TPStatus/{statusId} : Détail d’un statut pour un TP.
     * Retourne un TPStatus spécifique. Le TP et le cours associés sont implicites via le statut.
     *
     * @param statusId Identifiant du statut (TPStatus). (required)
     * @return Statut trouvé. (status code 200)
     * or Statut introuvable. (status code 404)
     * or Erreur interne. (status code 500)
     */
    @Operation(
            operationId = "getTPStatusById",
            summary = "Détail d’un statut pour un TP.",
            description = "Retourne un TPStatus spécifique. Le TP et le cours associés sont implicites via le statut.",
            tags = {"tp-status"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Statut trouvé.", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = heg.backendspring.models.TPStatusDto.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Statut introuvable."),
                    @ApiResponse(responseCode = "500", description = "Erreur interne.")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/TPStatus/{statusId}",
            produces = {"application/json"}
    )

    default ResponseEntity<heg.backendspring.models.TPStatusDto> getTPStatusById(
            @Parameter(name = "statusId", description = "Identifiant du statut (TPStatus).", required = true, in = ParameterIn.PATH) @PathVariable("statusId") Long statusId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : 1000, \"studentId\" : 300, \"tpId\" : 10, \"studentSubmission\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /TPStatus/{statusId} : Mise à jour d’un statut pour un TP.
     * Met à jour un TPStatus, notamment le champ studentSubmission (enum).
     *
     * @param statusId       Identifiant du statut (TPStatus). (required)
     * @param submissionType Nouvelle valeur du statut de soumission (StudentSubmissionType). (required)
     * @return Statut mis à jour. (status code 200)
     * or Données invalides. (status code 400)
     * or Statut introuvable. (status code 404)
     * or Erreur interne. (status code 500)
     */
    @Operation(
            operationId = "updateTPStatus",
            summary = "Mise à jour d’un statut pour un TP.",
            description = "Met à jour un TPStatus, notamment le champ studentSubmission (enum).",
            tags = {"tp-status"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Statut mis à jour.", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = heg.backendspring.models.TPStatusDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Données invalides."),
                    @ApiResponse(responseCode = "404", description = "Statut introuvable."),
                    @ApiResponse(responseCode = "500", description = "Erreur interne.")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/TPStatus/{statusId}",
            produces = {"application/json"}
    )

    default ResponseEntity<heg.backendspring.models.TPStatusDto> updateTPStatus(
            @Parameter(name = "statusId", description = "Identifiant du statut (TPStatus).", required = true, in = ParameterIn.PATH) @PathVariable("statusId") Long statusId,
            @NotNull @Parameter(name = "submissionType", description = "Nouvelle valeur du statut de soumission (StudentSubmissionType).", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "submissionType", required = true) String submissionType
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : 1000, \"studentId\" : 300, \"tpId\" : 10, \"studentSubmission\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
