@host = http://localhost:8088
@base = {{host}}/admin/courses

###
# 1) Get All Courses (admin)
# GET /admin/courses
###
GET {{base}}
Accept: application/json

###
# 2) Get Course by ID (admin)
# GET /admin/courses/{courseId}
###
GET {{base}}/1
Accept: application/json

###
# 3) Create a new course (admin)
# POST /admin/courses
###
POST {{base}}
Content-Type: application/json

{
  "id": null,
  "name": "Programmation collaborative",
  "code": "69-23",
  "semester": "AUTOMNE",
  "year_course": 2025,
  "teacher": "Stettler",
  "courseType": "JAVA",
  "studentList": [],
  "tpsList": [],
  "evaluations": []
}

###
# 4) Create another course (admin)
# POST /admin/courses
###
POST {{base}}
Content-Type: application/json

{
  "id": null,
  "name": "Progr",
  "code": "68-21",
  "semester": "AUTOMNE",
  "year_course": 2026,
  "teacher": "Stettler",
  "courseType": "JAVA",
  "studentList": [],
  "tpsList": [],
  "evaluations": []
}

###
# 5) Update an existing course (admin)
# PUT /admin/courses
# (le cours à mettre à jour est identifié par son "id" dans le body)
###
PUT {{base}}
Content-Type: application/json

{
  "id": 1,
  "name": "Programmation collaborative avancée",
  "code": "67-21",
  "semester": "PRINTEMPS",
  "year_course": 2025,
  "teacher": "Dupont",
  "courseType": "JAVA",
  "studentList": [],
  "tpsList": [],
  "evaluations": []
}

###
# 6) Delete a course (admin)
# DELETE /admin/courses/{courseId}
###
DELETE {{base}}/1
Accept: application/json
