@host = http://localhost:8088
@base = {{host}}/admin/v2/courses

###
# 1) Get Course by ID
# GET /admin/v2/courses/{id}
###
GET {{base}}/1
Accept: application/json

###
# 2) Get All Courses
# GET /admin/v2/courses/all
###
GET {{base}}/all
Accept: application/json

###
# 3) Create a new course
# POST /admin/v2/courses/addCourse
###
POST {{base}}/addCourse
Content-Type: application/json

{
  "id": null,
  "name": "Programmation collaborative",
  "code": "63-21",
  "semester": "AUTOMNE",
  "year_course": 2025,
  "teacher": "Stettler",
  "courseType": "Java",
  "studentList": [],
  "tpsList": [],
  "evaluations": []
}

###
# 4) Update an existing course
# PUT /admin/v2/courses/{id}
###
PUT {{base}}/1
Content-Type: application/json

{
  "id": 1,
  "name": "Programmation collaborative avancée",
  "code": "63-21",
  "semester": "PRINTEMPS",
  "year_course": 2025,
  "teacher": "Dupont",
  "courseType": "Java",
  "studentList": [],
  "tpsList": [],
  "evaluations": []
}

###
# 5) Delete a course
# DELETE /admin/v2/courses/{id}
###
DELETE {{base}}/1
Accept: application/json
